general:
  prefix_name: rdmc03 # this is a prefix for creating unique naming in Azure.

resource_group:
  name: dev-azure-ai-content-safety-rg
  location: australiaeast

azurerm_content_safety_service:
  name: dev-azure-content-safety-service
  sku: F0

azurerm_storage_account:
  name: devcontentsafsa

azurerm_storage_container:
  name: dev-images
  access_type: container

