general:
  prefix_name: rdmc01 # this is a prefix for creating unique naming in Azure.

resource_group:
  name: prod-azure-ai-content-safety-rg
  location: brazilsouth

azurerm_content_safety_service:
  name: prod-azure-content-safety-service
  sku: F0

azurerm_storage_account:
  name: prodaicontentsafetysa

azurerm_storage_container:
  name: prod-images
  access_type: container

